/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PasswordRecoveryLog } from "./PasswordRecoveryLog";
import { PasswordRecoveryLogCountArgs } from "./PasswordRecoveryLogCountArgs";
import { PasswordRecoveryLogFindManyArgs } from "./PasswordRecoveryLogFindManyArgs";
import { PasswordRecoveryLogFindUniqueArgs } from "./PasswordRecoveryLogFindUniqueArgs";
import { DeletePasswordRecoveryLogArgs } from "./DeletePasswordRecoveryLogArgs";
import { PasswordRecoveryLogService } from "../passwordRecoveryLog.service";
@graphql.Resolver(() => PasswordRecoveryLog)
export class PasswordRecoveryLogResolverBase {
  constructor(protected readonly service: PasswordRecoveryLogService) {}

  async _passwordRecoveryLogsMeta(
    @graphql.Args() args: PasswordRecoveryLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PasswordRecoveryLog])
  async passwordRecoveryLogs(
    @graphql.Args() args: PasswordRecoveryLogFindManyArgs
  ): Promise<PasswordRecoveryLog[]> {
    return this.service.passwordRecoveryLogs(args);
  }

  @graphql.Query(() => PasswordRecoveryLog, { nullable: true })
  async passwordRecoveryLog(
    @graphql.Args() args: PasswordRecoveryLogFindUniqueArgs
  ): Promise<PasswordRecoveryLog | null> {
    const result = await this.service.passwordRecoveryLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PasswordRecoveryLog)
  async deletePasswordRecoveryLog(
    @graphql.Args() args: DeletePasswordRecoveryLogArgs
  ): Promise<PasswordRecoveryLog | null> {
    try {
      return await this.service.deletePasswordRecoveryLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
